version: "3.6"
services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: on-failure
  #   networks:
  #     - sp-net
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   ports:
  #     - 80:80
  #     - 443:443
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  #   depends_on:
  #     - shinyproxy

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   restart: on-failure
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  shinyproxy:
    build:
      context: .
      dockerfile: ./shinyproxy/Dockerfile
    container_name: shinyproxy
    restart: on-failure
    networks:
      - sp-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8080

networks:
  sp-net:
    name: sp-net

volumes:
  shinyproxy_usage:
