proxy:
  port: 8080
  admin-groups: admins
  container-wait-time: 60000
  authentication: openid
  openid:
    auth-url: https://sergiobemar.eu.auth0.com/authorize
    token-url: https://sergiobemar.eu.auth0.com/oauth/token
    jwks-url: https://sergiobemar.eu.auth0.com/.well-known/jwks.json
    client-id: WMxfjLmZ0vxhaVBiJrdHwRDZeHZlCvzk
    client-secret: r1eJ7uww7OyIEJqnb_jv_Opmp4YuMlLSXSIElaGrjZj7N2iUfWbLa79Mm7Ucoe7U
#  saml:
#    idp-metadata-url: https://sergiobemar.eu.auth0.com/samlp/metadata/WMxfjLmZ0vxhaVBiJrdHwRDZeHZlCvzk
#    app-entity-id: urn:sergiobemar.eu.auth0.com
#    app-base-url: http://35.210.156.160
#    name-attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
#    roles-attribute: http://schemas.auth0.com/shinyproxy_roles
  docker:
    internal-networking: true
  specs:
    - id: 01_prediction
      display-name: Plataforma de Pedidos
      description: Plataforma para el reporting de pedidos realizados así como de la previsión de futuras ventas.
      container-image: sergiobemar/shiny-app-orders
      container-network: sp-net

logging:
  file: shinyproxy.log
