proxy:
  port: 8080
  admin-groups: admins
  container-wait-time: 60000
  hide-navbar: true
  authentication: openid
  openid:
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    token-url: https://www.googleapis.com/oauth2/v4/token
    jwks-url: https://www.googleapis.com/oauth2/v3/certs
    client-id: 984130808975-fkljqsfu43e3095b3r8pu7rqjc847gk8.apps.googleusercontent.com
    client-secret: w5nN3dhB5EfoAoslWl8mAUPd
    
    # Auth0
#     auth-url: https://sergiobemar.eu.auth0.com/authorize
#     token-url: https://sergiobemar.eu.auth0.com/oauth/token
#     jwks-url: https://sergiobemar.eu.auth0.com/.well-known/jwks.json
#     client-id: WMxfjLmZ0vxhaVBiJrdHwRDZeHZlCvzk
#     client-secret: r1eJ7uww7OyIEJqnb_jv_Opmp4YuMlLSXSIElaGrjZj7N2iUfWbLa79Mm7Ucoe7U
#     logout-url: https://www.google.com/accounts/Logout?continue=http://tfg.sergiobenito.es
  docker:
    internal-networking: true
  specs:
    - id: 01_prediction
      display-name: Plataforma de Pedidos
      description: Plataforma para el reporting de pedidos realizados así como de la previsión de futuras ventas.
      container-image: sergiobemar/shiny-app-orders
      container-network: sp-net
#server:
#  useForwardHeaders: true
logging:
  file: shinyproxy.log
