proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  container-wait-time: 60000
  users:
    - name: admin
      password: admin1234
      groups: admins
    - name: Alexa
      password: alexa
  docker:
    internal-networking: true
  specs:
    - id: 01_prediction
      display-name: Plataforma de Pedidos
      description: Plataforma para el reporting de pedidos realizados así como de la previsión de futuras ventas.
      container-image: sergiobemar/shiny-app-orders
      container-network: sp-net

logging:
  file: shinyproxy.log
